#cloud-config
write_files:
- path: /etc/nixos/host.nix
  permissions: '0644'
  content: |
    {pkgs, lib, config, ...}:
    {
      boot.initrd.extraUtilsCommands =
        ''
          # We need btrfs-convert
          copy_bin_and_libs ${pkgs.btrfs-progs}/bin/btrfs-convert
          # btrfs-progrs needs libgcc_s.so.1 or btrfs-convert will fail with pthread_cancel needing it.
          cp ${pkgs.btrfs-progs.stdenv.cc.cc.lib}/lib/libgcc_s.so.1 $out/lib/libgcc_s.so.1
        '';
      boot.initrd.postDeviceCommands =
        ''
          echo Converting ${config.fileSystems."/".device} to btrfs
          LD_PRELOAD=$extraUtils/lib/libgcc_s.so.1 btrfs-convert ${config.fileSystems."/".device}
        '';
    
      environment.systemPackages = with pkgs; [ vim ];
      fileSystems."/".fsType = lib.mkForce "btrfs";
      fileSystems."/boot" = {
        device = "/dev/sda15";
        fsType = "ext2";
      };
    }
runcmd:
- umount /boot/efi && rm -rf /boot/* && wipefs -f /dev/sda15 && mkfs.ext2 /dev/sda15
- curl https://raw.githubusercontent.com/elitak/nixos-infect/master/nixos-infect | PROVIDER=hetznercloud NIXOS_IMPORT=./host.nix NO_REBOOT=y NIX_CHANNEL=nixos-unstable bash 2>&1 | tee /tmp/infect.log
- mount /dev/sda15 /boot && /nix/var/nix/profiles/system/bin/switch-to-configuration boot && reboot
